apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinaple-auth-fe-deployment
  labels:
    app: pinaple-auth-fe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinaple-auth-fe
  template:
    metadata:
      labels:
        app: pinaple-auth-fe
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pinaple-auth-fe
        image: milanbella/pinaple-auth-fe
        imagePullPolicy: Always
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pinaple-auth-fe
spec:
  selector:
    app: pinaple-auth-fe
  ports:
    - protocol: TCP
      port: 80
