apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinaple-app-be-deployment
  labels:
    app: pinaple-app-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinaple-app-be
  template:
    metadata:
      labels:
        app: pinaple-app-be
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pinaple-app-be
        image: milanbella/pinaple-app-be
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pinaple-app-be
spec:
  selector:
    app: pinaple-app-be
  ports:
    - protocol: TCP
      port: 80
