apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinaple-img-deployment
  labels:
    app: pinaple-img
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinaple-img
  template:
    metadata:
      labels:
        app: pinaple-img
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pinaple-img
        image: milanbella/pinaple-img
        imagePullPolicy: Always
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pinaple-img
spec:
  selector:
    app: pinaple-img
  ports:
    - protocol: TCP
      port: 443
