apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinaple-auth-be-deployment
  labels:
    app: pinaple-auth-be
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinaple-auth-be
  template:
    metadata:
      labels:
        app: pinaple-auth-be
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pinaple-auth-be
        image: milanbella/pinaple-auth-be
        imagePullPolicy: Always
        ports:
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: pinaple-auth-be
spec:
  selector:
    app: pinaple-auth-be
  ports:
    - protocol: TCP
      port: 443
