apiVersion: apps/v1
kind: Deployment
metadata:
  name: pinaple-api-deployment
  labels:
    app: pinaple-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pinaple-api
  template:
    metadata:
      labels:
        app: pinaple-api
    spec:
      terminationGracePeriodSeconds: 30
      containers:
      - name: pinaple-api
        image: milanbella/pinaple-api
        imagePullPolicy: Always
        ports:
        - containerPort: 5100
---
apiVersion: v1
kind: Service
metadata:
  name: pinaple-api
spec:
  selector:
    app: pinaple-api
  ports:
    - protocol: TCP
      port: 5100
